version: '3'

services:
  user-service-app:
    container_name: user-service
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - user-db

  user-db:
    container_name: user-db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - user-db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=Aman123@
      - MYSQL_TCP_PORT=3306

volumes:
  user-db-volume:
